"""bugfixing 'no such table: users

Revision ID: 52017c58f0dc
Revises: 209cb2dc0a8d
Create Date: 2020-01-21 12:00:59.225147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52017c58f0dc'
down_revision = '209cb2dc0a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_guest_user_username', table_name='guest_user')
    op.drop_table('guest_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guest_user_username', 'guest_user', ['username'], unique=1)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
